### ISSUE TITLE
Fails with "conky: llua_load: /home/c0h2r/.conky/conky-pywal/lua/cpu.lua:9: attempt to index a nil value (global 'URxvtcolor090C10')" message.

### ISSUE THREAD

**Issue by c0h2r** [xexpanderx/conky-pywal#2]
In case someone has the same issue, it can be fixed by changing ' grep "*color" ' to ' grep "^*color" '. *Edit: in refresh_conky.sh

**Comment by xexpanderx** [comment]
What shell are you using? How do I replicate this?

**Comment by c0h2r** [comment]
Shell: zsh 5.8. Lua version: 5.3.5. PyWal version: 3.3.1. About the problem: do you have something like "URxvt*color06062F:   [100]#06062F" in your colors.Xresources? It seems to cause the problem. This value is never used, so I thought grepping it is not necessary. (Now everything seems to work fine.) Sorry, didn't mention the file I changed. It's refresh_conky.sh.

**Comment by xexpanderx** [comment]
Thanks for your reply.

This Conky is made with lua 5.1, so it may not work as expected with lua 5.3.x. Please see this: https://github.com/xexpanderx/conky-pywal/issues/1

For the colors.Xresources, no, I do not have that.

I guess it is better to add "^", to match *color at beginning of a line. Thx for this tip!
